### ISSUE TITLE
slack.files.upload not working

### ISSUE THREAD

**Issue by edenlu** [smallwins/slack#109]
First, in the documentation, it specifies the parameter like this 
`slack.files.upload({token})   //only one parameter, i guess it's not completed`

Second, I try using 
` slack.files.upload({token, title, filename, file})` 
to upload, where "file" is obtained from fs.readFileStream(fileName). 
But the response return from slack is {no_file_data}

However, I use these same variables to send direct request to the API 
```
request.post({
	     url: 'https://slack.com/api/files.upload',
	     formData: {
	           token: slackToken,
	           title: specName,
	           filename: fileName,
	           filetype: "auto",
	           channels: "#general",
	           file: fd
	       }
	   }
```

it successfully upload the image file to my channel, so I suspect this may be a bug

Thanks,
Eden

**Comment by edenlu** [comment]
One additional request that is not related to this problem:
Is there a way to use a different username and icon_emoji when upload image?

**Comment by brianleroux** [comment]
Thx for the report! This is a good one. TL;DR: this one method in the Slack Web API that has different `Content-Type` requirements and expectations than the rest of the API. 

https://api.slack.com/methods/files.upload

Your first concern about the README documentation only specifying `token` is a result of our docs being scraped from the official docs; `token` is the only required parameter for this API call so the docs are rendering correctly (if confusingly!). Might be good to code a corner case note for this particular method to read: `slack.files.upload({token, [file|content]})` instead. 

As to function: your workaround is the best thing to do at the moment. I'll look at cutting a branch today that uses `multipart/form-data` instead of `application/x-www-form-urlencoded` for this call which should fix it.

**Comment by brianleroux** [comment]
Quick update: I have a mostly working solution branch. This was trickier than expected (what else is new in software eh) but should be ready to cut a release early next week. 

Thx again for reporting. I'll update when the branch is ready. 👍

**Comment by brianleroux** [comment]
That was fun! Here's an example script:

```javascript
var slack = require('slack')
var fs = require('fs')

var file = fs.createReadStream(__dirname + '/test-109.png') // <--make sure that png exists
var token = 'xoxb-xxx' // <-- your token here

slack.files.upload({
  token, 
  file, 
}, console.log)
```

**Comment by lifeeric** [comment]
here is the solution: https://stackoverflow.com/questions/43607011/upload-image-to-slack-with-axios/66506921#66506921

```js
const fs = require("fs"); 
const axios = require("axios");
const FormData = require("form-data");


const form = new FormData();

form.append("token", 'token here');
form.append("channels", channelId);
form.append("file", fs.createReadStream(__dirname + "/aapl.png"), 'file name');

try {
  const res = await axios.post("https://slack.com/api/files.upload", form, {
    headers: form.getHeaders(),
  });
} catch (err) {
  throw new Error(err);
}
```
