### ISSUE TITLE
Apache 2.0 License

### ISSUE THREAD

**Issue by CharlieHess** [smallwins/slack#110]
Opening this issue mainly for discussion. We're considering using this in the Slack desktop app but have some questions about the license. Reason being that I'm using [`patch-package`](https://github.com/ds300/patch-package) to modify your `api.json` file to expose private Slack APIs not exposed in the documentation. This kind of post-hoc patching, although trivial to do, may not be within the constraints of Apache 2.0.

So, I guess my question is:

1. Was the Apache choice intentional?
1. Any chance of switching to a more permissive license? (MIT, BSD, ISC, etc.)
1. If not, how about a constructor param that lets us append private APIs, something like

``` js
const slack = new Slack({ 
  extensions: [{
    users: { privateApi: ['token', 'customParam'] }
  }]
});
slack.users.privateApi({ token: '123', customParam: true });
```

**Comment by brianleroux** [comment]
1. Apache 2.0 is very deliberately chosen! It tends to be the most corporate friendly as that it has a patent clause. I think your use case is fully within the bounds of the license (as I understand it) modification is fine. 

2. Rather than switch we can add a LICENSE --- super common to see software offered under multiple permissive licenses. I'm not sure what the process is to do that tho! I'll follow with some research there.

3. I think we could probably support this too; wouldn't be much code!

**Comment by brianleroux** [comment]
Update: just asked around a bit and the case you describe is ok. Modification is (obviously) allowed and if you plan on redistributing the software you'd have to mention said changes in a NOTICE file. 

(But it doesn't sound like you'll be redistributing it so much as just using it.)

**Comment by CharlieHess** [comment]
Alright, I'll close this then! Thanks for the confirmation @brianleroux
