### ISSUE TITLE
No file for browser in npm package

### ISSUE THREAD

**Issue by sapkra** [smallwins/slack#113]
Can you please add the `slack.js` and `slack.min.js` to the npm package.

btw. there is also no documentation how to use this libary in the browser.

**Comment by brianleroux** [comment]
hey @sapkra browser supported! https://github.com/smallwins/slack/blob/master/package.json#L7

depending on whether you use webpack, parcel, and browserify should all pick this module up using the `browser` field in the package.json linked above. super agree we need better browser usage docs.

what would you expect for docs?

**Comment by brianleroux** [comment]
also an example of doing a standalone browser build here https://github.com/smallwins/slack/blob/master/scripts/browser-pkg using browserify

**Comment by sapkra** [comment]
Thanks for your fast answer. I built the file by myself with your `browser-pkg` script. But it still would be great to have this standalone browser build in the npm package so that it will be easy to update it.

**Comment by brianleroux** [comment]
Ah, I see, interestingly this reason is precisely why _we don't_ ship the built source. We can't say what your build process is so we just ship the latest source code to npm so you can stay up to date with it. 

The build part is a userland concern …which has been growing more complex with time. Some projects like TypeScript. Some want Flow. Some folks just use basic commonjs but others prefer to build things with esmodules. Its not really easy for us to have a say, and it really isn't a goal of this project to try to solve that part of the developer experience, so this project just ships vanilla source code that works well (tested) in both Node and the Browser and otherwise we leave the build part to the users to decide what works best for them. Otherwise we could be shipping all sorts of stuff and a big goal for this project is to be as small as possible). (Hope this helps explain the reasoning a bit!)

Do you think it would have been helpful if we had a guide in the readme for using `slack` with browserify, parcel and/or webpack?

**Comment by sapkra** [comment]
Ahh okay, I understand!
In my opinion it's normal to add a documentation how it implement a library. If you say you support browsers then of cause you have to add a documentation for it. ;D
So yeah, a documentation for webpack & co. is definitely helpful for everyone who wants to use this library on the client.

**Comment by brianleroux** [comment]
cheers, thx for the feedback!
