### ISSUE TITLE
Typescript defs don't support OO style pattern

### ISSUE THREAD

**Issue by natew** [smallwins/slack#115]
Just noting, it seems to only export the namepsace. Perhaps I'm missing it though.

**Comment by danprince** [comment]
Hey @natew. I'm afraid you're right! I never got round to adding the definitions for the OO style, because I never use it myself.

Happy to take a stab at rewriting [the generator](https://github.com/smallwins/slack/blob/master/scripts/generate-types) if you have an idea for what the ideal exports would look like (ideally without duplicating everything).

**Comment by brianleroux** [comment]
I don't have enough TypeScript knowledge to know what the right interface would be but super open to adding it in if you can provide me a quick example of what you would have expected to get started from @natew 🙏

**Comment by danprince** [comment]
I think it should just be a case of also exporting a class with the params for each method tweaked so that the token isn't expected/required.

I'll try and take a stab at it over the weekend.

```ts
declare module "slack" {
  export let api: {
    test(params: Api.Test.Params): Promise<Api.Test.Response>
    test(params: Api.Test.Params, callback: (params: Api.Test.Params) => void): void
  }

  // ...
}
```

Needs to become

```ts
declare module "slack" {
  export let api: {
    test(params: Api.Test.Params): Promise<Api.Test.Response>
    test(params: Api.Test.Params, callback: (params: Api.Test.Params) => void): void
  }

  export = class Slack {
    token: string;
    constructor(token: string);

    test(params: Api.Test.Params): Promise<Api.Test.Response>;
    test(params: Api.Test.Params, callback: (params: Api.Test.Params) => void): void;
  }
}
```

**Comment by danprince** [comment]
Got the proof of concept in [`oo-type-defs`](https://github.com/smallwins/slack/tree/oo-type-defs).

Turns out you can't use both named exports and a commonjs export inside one module declaration, so I ended up throwing the stateless versions onto the class as static methods. Looks more like this now:

```ts
export = class Slack {
  token: string;
  constructor(token: string);

  static api = {
    test(params: Api.Test.Params): Promise<Api.Test.Response>;
    test(params: Api.Test.Params, callback: (params: Api.Test.Params) => void): void;
  };
 
  api = {
    test(params: Api.Test.Params): Promise<Api.Test.Response>;
    test(params: Api.Test.Params, callback: (params: Api.Test.Params) => void): void;
  };
}
```

[Made the token parameter optional](https://github.com/smallwins/slack/commit/cd9f302ef567df79da1b6b825ed4f0cdb0274a51) so that the original parameter interfaces are correct for both versions, although I would like to sort this out before merging, because it also means both versions are slightly wrong. The token parameter shouldn't be there at all on the instance methods and it should be required on the static ones.

Also shaved a few hundred lines by moving the common params/responses into shared interfaces that the others can extend, but this is still quite a bit bigger than the original type defs.

**Comment by brianleroux** [comment]
Right on thx for hackin' on this Dan! I need to levelup and learn Typescript a bit better. Could it make sense to have typedef files and let ppl opt into the syntax path best suited to their project needs? (I clearly have no idea. Kinda not surprised the super flexible nature of JS is tricky to capture in static annotations.)

**Comment by danprince** [comment]
I think it would only work if the types were published as two separate packages, then you could just install the one you wanted—or have them manually include it from inside this library, as part of their tsconfig.json.

I'll see whether I can get both styles playing nice in one file, if not, can look at one of those options.

**Comment by brianleroux** [comment]
I have no strong opinions about this but I'm issue gardening and closing up stale threads. If there's reason to reopen to continue tracking pls fee free!

**Comment by natew** [comment]
Would be nice!

**Comment by pleerock** [comment]
@brianleroux its good for you to have zero issues opened, but its not good for a project and community. This issue is definitely  **an issue** and must be fixed, or at least being opened until it is fixed.

@danprince why wouldn't #124 work?

**Comment by danprince** [comment]
@pleerock Thanks for this! Here are a few concerns I still have with this kind of approach.

We don't maintain the `slack.d.ts` file manually, it's generated by scraping the docs like the rest of the library (see [scripts/generate-types](https://github.com/smallwins/slack/blob/master/scripts/generate-types)) — That's also why many of the types (`Params`, `Response` etc) have index signatures or generic types (`any` vs `string`) rather than detailed interfaces. 

We could get more accurate types by generating them from Slack's [OpenAPI definitions](https://api.slack.com/specs/openapi/v2/slack_web.json) but that's a pretty big job. Especially with the handwritten code generator.

This version with a default export doesn't support the static, stateless versions of the methods. E.g you can't do:

```ts
import slack from "slack";
slack.api.test()
```

Technically, this library doesn't have a default export at all, just a CommonJS one.

https://github.com/smallwins/slack/blob/ac2ccdfef8e1f509127f07ed23e0d383cfa47941/index.js#L9

Adding a default export to the declarations can keep the compiler happy, but look at the code that the above example generates:

```js
"use strict";
exports.__esModule = true;
var slack_1 = require("slack");
slack_1["default"].api.test();
```

`slack_1["default"]` is always going to be undefined whilst the actual module is authored with CommonJS exports.

To properly properly support this pattern, we'd need to switch to declaring a CommonJS export for a single object that supported both patterns. 

```ts
declare module "slack" {
  export = Slack // where Slack supports new Slack().api.test and Slack.api.test
}
```

However, that ends up being a breaking change that forces everyone using ESM import syntax to rewrite their code:

```ts
import * as slack from "slack";
import { api } from "slack";

// becomes

import slack = require("slack");
import { api } = require("slack");
```

I agree that this is a bug and it does need to be fixed. I just don't have enough time to fix it myself. 
Happy to help out if you want to try and make these changes though!

To be fair to Brian, even after I proposed some solutions above, the issue had zero engagement until it was closed. It's pretty standard practice to close stale issues, but we can re-open this one now if you want to keep hacking in your PR.

**Comment by danprince** [comment]
@pleerock Sorry! I know it's not ideal, but there's not a straightforward solution either.

The hacks don't need to be too crazy if you want to use `new Slack` though.

```ts
import * as Slack from "slack";

let slack = new (Slack as any)() as typeof Slack;
```

You're probably only going to be creating a single instance and sharing it throughout your codebase, so it's not really much extra code.

**Comment by pleerock** [comment]
Yeap so this is what I call crazy hacks 😆

**Comment by danprince** [comment]
It's still type safe though. Using `typeof` and `any` is pretty standard in most TS codebases that interop with JS. Don't really qualify as crazy to me, just inconvenient.

**Comment by danprince** [comment]
If adding an explaining comment is too much to justify having type definitions, then fair enough. Each to their own.

I'll make sure to ping you here when we support type definitions for the class approach.
