### ISSUE TITLE
Can't Handle Errors Gracefully

### ISSUE THREAD

**Issue by samcaplat** [smallwins/slack#116]
Thanks for such a great library.

I'm very confused about how to correctly check errors. I'm using `request-promise` throughout my application, which seems to be fairly standard, but this library doesn't return errors in the same way.

I've purposefully created a 'missing params: text' error in a 'slack.chat.postMessage' request:

```javascript
console.log(error.statusCode) // undefined
console.log(error.statusMessage) // undefined
console.log(error.messages) // (as per docs) undefined
console.log(error.message) // chat.postMessage missing params: text
```

How can I access more information about errors?

Thanks,
Sam

**Comment by brianleroux** [comment]
First of all: thx for reporting. We def need better docs on proper ways to handle error conditions. Appreciate if you could help me zero in on what we need to clarify. 

I'm going to try to address these one by one:

- `error.statusCode` is not there because the client library just fails if you give it bad input …with just a vanilla javascript [error](https://github.com/smallwins/slack/blob/master/src/_validate.js#L9); Usually status codes refer to http status codes but we're not even making one if there's bad input. That standard issue javascript error gives you the information you need to fix the problem: why it occurred and the line it occurred on. But I am super open to making it better. Thoughts?
- `error.messages` is confusing! we need to fix our docs on that. This property is a quirk of the slack api `slack.dialog.open` and that is the only time this information is populated 
- I'm not sure what you'd expect for `error.description` and `error.number` (those properties are unfamiliar to me) ---what would you expect there? (Longer form version of error.message maybe?) Also not confident we'd want to get into enumerating all possible errors with a custom code on our side.

**Comment by samcaplat** [comment]
Hi Brian, sorry for my delay!

The vanilla error is fine when this library is being used on its own, but handling the error when chaining requests with Promises is much more difficult. All of the other libraries in that chain use `request` or `request-promise` except for Slack. Usually I can do a simple if-else or switch statement which is appropriate for all errors regardless of which library it's from:

```javascript
if (error.statusCode === 422) {
  // handle error
}

switch (error.statusCode) {
  case 422:
    // handle error
    break
}
```

But when I add Slack into the chain, I can't handle errors in the same way. I need to check if the error contains specific text:

```javascript
if (error.includes('422') {
  // handle error
}
```

I'm open to the idea that I'm not handling this in the best way. It would be really interesting to do some speed comparisons between `tiny-json-http` and `request-promise` to see what the difference is, and whether it's worth offering the option to users.

I misinterpreted what the `error.number` and `error.description` properties are for, so you can ignore those.

**Comment by brianleroux** [comment]
hmmm, what calls do you do that render a `422`? (slack mostly doesn't use http status codes… or didn't anyhow but maybe they changed that)

**Comment by brianleroux** [comment]
closing for now but feel free to reopen if you'd like to continue pursuing a change here
