### ISSUE TITLE
Specify Token Once?

### ISSUE THREAD

**Issue by TuckerWhitehouse** [smallwins/slack#19]
Would benefit from being able to instantiate like a class, passing the token once, instead of for each method.
e.g. `new Slack({ token: "..." })` as @tjhorner suggests below.

**Comment by tjhorner** [comment]
:+1: This would be very handy and a lot cleaner.

**Comment by brianleroux** [comment]
Hey everyone! Thx for the feedback. Its super easy to wrap this API to do that instead of pushing it to a *global* env var when a token is really just for one auth. Also consider the browser use case: no env vars there. (You can always envify but that again would be more approp for userland.)

**Comment by tjhorner** [comment]
@TuckerWhitehouse is not only suggesting environment variables, but just globally defining it, in something like `new Slack({ token: "xoxb-whatever" })`

**Comment by TuckerWhitehouse** [comment]
@tjhorner :+1:

**Comment by brianleroux** [comment]
ah! ok, so not a `global` but rather you want _instances_. this is p easy to add…let me get back to you shortly about this :+1:

**Comment by brianleroux** [comment]
not sure how I feel about this api. this library was very deliberately stateless and mostly, where it makes sense, functional. this addition is interesting and maybe useful so looking for your feedback! here's an example using it:

![screen shot 2016-02-19 at 11 00 09 am](https://cloud.githubusercontent.com/assets/990/13185913/74105f7e-d6f8-11e5-8042-6c047c4b8617.png)

the entire slack api is mirrored so that _if_ a method required an oauth token its applied (all other params still required if they are required and if no other params are required you still have to pass an empty obj tho this would be fairly trivial to change)

**Comment by brianleroux** [comment]
lmk if this works or not in a new issue!

**Comment by TuckerWhitehouse** [comment]
Thanks @brianleroux, certainly an improvement.
