### ISSUE TITLE
Consider checking res.ok instead of res.error

### ISSUE THREAD

**Issue by delasteve** [smallwins/slack#51]
The official Slack Web API documentation suggests: 
> Callers should always check the value of the `ok` params in the response

The `_exec.js` and `_exec-browser.js` both check for `res.error` instead of `res.ok`. 

Suggestion:
- Use `res.ok` to check if there should be an error
- Send the entire `res` object into the error rather than just `res.error`
- Don't delete `res.ok` in `_exec-browser.js` (leave `res` alone)
- Consider handling both callbacks in the same manner (`_exec-browser.js` does a lot more while `_exec.js` doesn't worry about anything besides errors)
  - Preferably, handle the callback the way `_exec.js` does

If this functionality is wanted, I will create a PR for it.

Files:
https://github.com/smallwins/slack/blob/master/src/_exec.js#L29
https://github.com/smallwins/slack/blob/master/src/_exec-browser.js#L18
https://github.com/smallwins/slack/blob/master/src/_exec-browser.js#L28

Reference:
https://api.slack.com/web#basics
https://api.slack.com/methods/chat.postMessage#errors (or any Web API method)

**Comment by brianleroux** [comment]
Cool: thx. These are good suggestions and align nicely with some improvements I've been thinking about. 

I too would also like to align `_exec` and `_exec-browser`. We recently added `tiny-json-http` for the network stuff in `_exec` and it *should* be browserifyable (but I have not tested this yet). Essentially this means we get rid of _exec-browser and its corresponding entry in package.json and then run the tests. =) (This also means we lose a dependency and the package gets smaller yay.)

Errors: I deliberately chose the surface the error string that Slack sends back as a javascript `Error` so we get clean stack traces in failure scenarios. This has been enormously beneficial in our own bot debugging and regular development so wouldn't want to lose that. Passing anything other than error in the callback would be breaking change. That said, I'd super be into enhancing that error object instance with the original payload as a property or something like that.

**Comment by brianleroux** [comment]
Couldn't help but test it out and it worked! Only one `_exec` now. =)

https://github.com/smallwins/slack/commit/8a91ea0755b6205618899618d0af6b5cf4a12ed1

LMK what you think about the `Error`!

**Comment by delasteve** [comment]
Awesome work.

So, I was toying with the idea (since I knew it would break current functionality) of sending `res` in the callback.

e.g.:
```js
else if (res.error) {
  callback(Error(res.error), res)
}
```

Now, this breaks the node-style callbacks. If you were to ever do promises (one suggestion at a time!), you wouldn't be able to pass both in.

**Comment by brianleroux** [comment]
Yeah, I def don't want to break system symmetry with Node errbacks. That too was deliberately to make this an "easy(er) to reason about" system. Promise libraries or async should be a user land choice not a library choice since these opinions are murky and often conflict. Just this week we had a dependency two levels deep clobber the native promise breaking how other libraries we depend on thought it should behave. This wasn't code of ours but it broke our builds. Nightmare! 

We could do something like 
```
var e = Error(res.error)
e.originalPayload = res
```

?

**Comment by delasteve** [comment]
Thought about it over the weekend and had a couple ideas.

1. I think the `res.originalPayload` is fine. That would keep current functionality. What about, though, setting a flag that allows the end user to have the `Error(res)` passed in? I would have to look into more how to accomplish this, as I haven't dug too deeply into the codebase.
2. Promises and callbacks don't have to conflict. Bluebird makes this easy with it's `asCallback` api. You can read more here: http://bluebirdjs.com/docs/api/ascallback.html

Thoughts?

**Comment by brianleroux** [comment]
The built-in JavaScript `Error` constructor only accepts a string which it uses for a `message` property. While you could serialize JSON into it that would be odd.

As to promises and callbacks: indeed they do not have to conflict. The only way to guarantee that is to make sure they are only used at the app level / user land. This means we do not want to opt downstream users into a particular solution (because they might want to use a different one). If someone using this library uses Q, BlueBird, RSVP or other solution: that is up to them! Any would work well with a node err back library such as this one. 

Going to close this thread for now but pls feel free to share more ideas or questions in the comments! 🍻
