### ISSUE TITLE
keep .env file private

### ISSUE THREAD

**Issue by ORESoftware** [smallwins/slack#52]
Support question -

we are supposed to put an .env file in the root of our project when using require('slack'), however, if this is public info, couldn't a malicious person abuse our slack credentials?

How to mitigate this?

**Comment by ORESoftware** [comment]
perhaps we only need this .env file to test this library itself, and not to use the library in our application, if so I guess we can scratch this issue :)

**Comment by brianleroux** [comment]
Correct! Often recommended is keeping secrets in environment variables. More good tips here https://12factor.net

**Comment by ORESoftware** [comment]
Ok I think I get it, thanks

**Comment by delasteve** [comment]
> What I am a little unclear on however, is, do we need these env variables for using this library or just testing this library?

@ORESoftware `.env` files should be ignored. You should be kind and create an `.env.example` file so that other users can see what variables they do need. That said, you don't *need* the environment variables to make this work. You could very well use the library like so:

```js
bot.listen({token: 'xoxb-thisisabotkeyandyoushouldntputthisdirectlyinyourcode'})
```

Doing so leads to checking in your bot token to the repository which others can then abuse, among other various security concerns. Libraries are out there to make this painless, such as, https://github.com/motdotla/dotenv. 

>The docs make it seem like these env variables are only needed if we were to run the tests in this library against this library.

I'm on the side that the docs do a good job showing best practice with environment variables. If I were the maintainer, I would rather people open issues like you have and have best practice explained to them, than have the developer end up doing something silly. Read this article if you haven't: https://wptavern.com/ryan-hellyers-aws-nightmare-leaked-access-keys-result-in-a-6000-bill-overnight
