### ISSUE TITLE
no response_metadata? 

### ISSUE THREAD

**Issue by Ferrari** [smallwins/slack#82]
Based on [slack dialog document](https://api.slack.com/methods/dialog.open), it will append `response_metadata` when API return `validation_errors` error.

But seem only return `error` field: https://github.com/smallwins/slack/blob/e80a3a45fa9afd68743a3d66a58ad8f3f67218e8/src/_exec.js#L48-L50

it that possible return `response_metadata` in `validation_errors` error case?

**Comment by brianleroux** [comment]
Oh! Absolutely we need to do this. `Error` can have arbitrary properties so we could do something like this:

```javascript
let err = Error(res.body.error)
err.messages = res.body.response_metadata.messages
callback(err)
```

What do you think? 

cc @mbrevoort

**Comment by mbrevoort** [comment]
I like it. `response_metadata` seems like the standard place that more specific error details will be returned for now on (based on conversations with Slack team). I like this better than trying to jam it into `message` as a string.

**Comment by mbrevoort** [comment]
We could also pass the body even on error so that we don’t hide any context unnecessarily. The caller would of course need to consider that body may be undefined depending on the error.

`callback(err, res.body)`

**Comment by Ferrari** [comment]
Maybe `callback(err, res.body)` would be better if slack use other error format in the future?

**Comment by brianleroux** [comment]
Hmmm, seems like res.body would be the most flexible method to achieve this and future additions— but does it work with the Promise code path ? (I can answer this myself when I get to a machine!)

**Comment by brianleroux** [comment]
Update: yeah pretty sure we can’t pass body this way and have access to the messages if there’s a  Promise involved. I’m ok with that. Keeps the Error code path isolated in calling clients.

https://github.com/ljharb/util.promisify/blob/master/implementation.js#L60

**Comment by brianleroux** [comment]
Update 2: for kicks I added Error.messages from my phone 📱 and the CI built it. Still not at a computer so I can publish to the npm registry—need to automate that!

**Comment by brianleroux** [comment]
🆗 published in `slack@9.0.3`

thx all 🙏

**Comment by danprince** [comment]
Thanks for all the work on this library! Since promise support was added, we switched over from `slack-promise` and it's great to see that conversations and dialogs are already here!

I know it's early days for this error format, but I've been building out some features with dialogs and was expecting to see `error.response_metadata.messages` on the error object, then read through the code that throws and ended up here.

How would you feel about a PR that exposed the original Slack response body on the error so that it was always possible to get back to the raw data, so that this package doesn't always have to think about forwarding additional error properties like this when the API changes?

```js
var e = Error(res.body.error)
err.slack_response = res.body
```

Another option might be to merge the response body into the error object, so that for most intents and purposes the thrown error looked like the one that Slack describes in the docs.

```js
var e = Error(res.body.error)
Object.assign(e, res.body)
```

However, this has the potential to get a bit messy if Slack added a response level field that collided with one of the native error properties.

At the very least, it'd be good to document the `messages` property somewhere. Let me know if any of these options might work for you and I'll create a PR.

**Comment by brianleroux** [comment]
I am just not sure! Every time I land code for a future hypothetical problem it almost always becomes more problematic than helpful. Long range backwards compat is very important to me! 

A blind `Object.assign` opens the lib up to potential clobbers on the prototype so cannot do that. I personally find `err.slack_response` crufty and our own made up thing so I'm not inclined to go that road since we'd have to document anyhow. 

The `Error` having a `messages` property is easily discover-able and facilitates the problem(s) today but, again you are right, we need to document this. 

Currently we have relied on Slack Docs but this case is special and should probably get a mention in the `readme.tmpl` (which we then use to generate `readme.md`).

**Comment by danprince** [comment]
Yep, that all sounds well reasoned to me.

I guess that if the `response_metadata` format changed significantly (e.g. diversified into multiple types of messages), then we could expose the entire object as `error.metadata`.
